### ISSUE TITLE
Error when a track is queued on an active playlist

### ISSUE THREAD

**Issue by twcapps** [jaedb/spotmop#108]
when I try to queue an individual track on an active playlist (drag to left column "add to queue") I receive the below error in the console (chrome browser)

Server returned error: 

```
code: -32602
data:
message: "'NoneType' object is not iterable"
traceback: "Traceback (most recent call last):
 File "/usr/lib/python2.7/dist-packages/mopidy/internal/jsonrpc.py", line 133, in   _handle_single_request
result = self._unwrap_result(result)
 File "/usr/lib/python2.7/dist-packages/mopidy/internal/jsonrpc.py", line 222, in _unwrap_result
result = result.get()
 File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
compat.reraise(*self._data['exc_info'])
 File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
exec('raise tp, value, tb')
 File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
response = self._handle_receive(message)
 File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
return callee(*message['args'], **message['kwargs'])
 File "/usr/lib/python2.7/dist-packages/mopidy/core/tracklist.py", line 431, in add
track_map = self.core.library.lookup(uris=uris)
 File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 231, in lookup
 for u in backend_uris:
TypeError: 'NoneType' object is not iterable
type: "TypeError"
message:"Invalid params"
```

**Comment by jaedb** [comment]
@twcapps thanks for the error log, that certainly helps. Can you please provide some extra info about your environment? IE: modify version, spotmop version, Linux version, etc?

**Comment by jaedb** [comment]
@twcapps (or anyone else) have you continued to experience this issue? I'm having trouble replicating it.

**Comment by bartsidee** [comment]
yes it is still an issue
Mopidy 2.0.0
Port 80
Raspbian GNU/Linux 8 (jessie)

**Comment by jaedb** [comment]
@bartsidee Are you able to try this and select the track first, ie click once (it'll highlight yellow) and then try dragging and dropping?

**Comment by jaedb** [comment]
I've just pushed to the `develop` branch that should fix this. It'd be great if you could confirm this is working before I release to live :-)

**Comment by bartsidee** [comment]
Just pulled from the latest develop, if I first click the track and the drag it now indeeds works. Still throws an error when a single song is directly dragged (without clicking first). 

As a recommendation it would be nice to not necessary use the click+drag, but just the drag as it is a more user friendly.

**Comment by jaedb** [comment]
Partially resolved in latest release, 2.8.0 (ef01ee4)

**Comment by jaedb** [comment]
Resolved in [v2.9](https://github.com/jaedb/spotmop/releases/tag/2.9)
